name: Hello World

on:
  push:
    branches:
      - main

jobs:
  demo:
    runs-on: ubuntu-latest
    
    steps:
      - name: run number with offset
        env:
          NUM: 10
        run: |
          echo "GITHUB_RUN_NUMBER_WITH_OFFSET=$(($NUM + 200))" >> $GITHUB_ENV

      - name: 'Perform Operation with ID ${{ env.GITHUB_RUN_NUMBER_WITH_OFFSET }}'
        run: echo "Success!"
